import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import ReactQueryProvider from '@/store/reactQueryProvider';
import Header from '@/layouts/Header';

import '@/styles/globals.css';

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <main className="flex flex-col flex-1 bg-gray100">
            <Header />
            {children}
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
